/** Declaration file generated by dts-gen */
import * as m from 'd3';
export function weightedVoronoi(...args: any[]): any;

export namespace weightedVoronoi {
  const prototype: {};
}
declare module 'd3' {
  export function weightedVoronoi<T = any>(): WVLayout<T>;

  export interface WVLayout<T> {
    (sites: T[]): Array<WVPolygon<T>>;
    x(fx: (d: T) => number): this;
    x(): (d: T) => number;
    y(fy: (d: T) => number): this;
    y(): (d: T) => number;
    weight(fw: (d: T) => number): this;
    weight(): (d: T) => number;
    clip(pts: [number, number][]);
    clip(): [number, number][];
    extent(
      ext: [
        [[number, number], [number, number]],
        [[number, number], [number, number]]
      ]
    ): this;
    extent(): [
      [[number, number], [number, number]],
      [[number, number], [number, number]]
    ];
    size(sz: [[number, number], [number, number]]): this;
    size(): [[number, number], [number, number]];
  }
  export interface WVVertex<T> {
    x: number;
    y: number;
    weight: number;
    neigbours: Array<WVVertex<T>>;
    originalObject: T;
    polygon: WVPolygon<T>;
    nonClippedPolygon: WVPolygon<T>;
  }
  export interface WVPolygon<T> extends Array<[number, number]> {
    site: WVVertex<T>;
  }
}
